# Generated by Django 4.0.6 on 2022-07-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review_movie_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=350, unique=True),
        ),
    ]
